tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  - name: utils
    before: |
      sudo apt-get install tree
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.5
  # https://docs.aws.amazon.com/powershell/v5/userguide/install-aws.tools-on-linux-macos.html
  # https://docs.aws.amazon.com/powershell/v5/reference/
  - name: AWS-powershell
    before: |
      ./bin/powershell_cli_install.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
