#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-sample2"

# no-execute-changeset 是為了可以手動確認檢查Change set 
aws cloudformation deploy \
  --template-file template.yaml \
  --no-execute-changeset \ 
  --region us-east-1 \
  --stack-name $STACK_NAME
